In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Mengambil Data Covid19
df = pd.read_csv('../input/covid19-indonesia/covid_19_indonesia_time_series_all.csv')

In [3]:
#Menampilkan Column Name
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21759 entries, 0 to 21758
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         21759 non-null  object
 1   Location ISO Code            21759 non-null  object
 2   Location                     21759 non-null  object
 3   New Cases                    21759 non-null  int64
 4   New Deaths                   21759 non-null  int64
 5   New Recovered                21759 non-null  int64
 6   New Active Cases             21759 non-null  int64
 7   Total Cases                  21759 non-null  int64
 8   Total Deaths                 21759 non-null  int64
 9   Total Recovered              21759 non-null  int64
 10  Total Active Cases           21759 non-null  int64
 11  Location Level               21759 non-null  object
 12  City or Regency              0 non-null      float64
 13  Province                     21117 non-null  object
 14  Country                      21759 non-null  object
 15  Continent                    21759 non-null  object
 16  Island                       21117 non-null  object
 17  Time Zone                    21117 non-null  object
 18  Special Status               3123 non-null   object
 19  Total Regencies              21759 non-null  int64
 20  Total Cities                 21145 non-null  float64
 21  Total Districts              21759 non-null  int64
 22  Total Urban Villages         21142 non-null  float64
 23  Total Rural Villages         21117 non-null  float64
 24  Area (km2)                   21759 non-null  int64
 25  Population                   21759 non-null  int64
 26  Population Density           21759 non-null  float64
 27  Longitude                    21759 non-null  float64
 28  Latitude                     21759 non-null  float64
 29  New Cases per Million        21759 non-null  float64
 30  Total Cases per Million      21759 non-null  float64
 31  New Deaths per Million       21759 non-null  float64
 32  Total Deaths per Million     21759 non-null  float64
 33  Total Deaths per 100rb       21759 non-null  float64
 34  Case Fatality Rate           21759 non-null  object
 35  Case Recovered Rate          21759 non-null  object
 36  Growth Factor of New Cases   20572 non-null  float64
 37  Growth Factor of New Deaths  19292 non-null  float64
dtypes: float64(14), int64(12), object(12)
memory usage: 6.3+ MB

In [4]:
#Menampilkan 5 baris teratas
df.head()

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,41,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,105.13%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,41,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,100.00%,1.0,1.0
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,2,0,3,...,0.511648,0.16,0.33,0.0,0.00,0.00,0.00%,150.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,41,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,95.35%,1.0,1.0

In [5]:
#Missing Vale (Jumlah Entry NULL di tiap baris kolom)
df.isna().sum()

Date                               0
Location ISO Code                  0
Location                           0
New Cases                          0
New Deaths                         0
New Recovered                      0
New Active Cases                   0
Total Cases                        0
Total Deaths                       0
Total Recovered                    0
Total Active Cases                 0
Location Level                     0
City or Regency                21759
Province                         642
Country                            0
Continent                          0
Island                           642
Time Zone                        642
Special Status                 18636
Total Regencies                    0
Total Cities                     614
Total Districts                    0
Total Urban Villages             617
Total Rural Villages             642
Area (km2)                         0
Population                         0
Population Density                 0
Longitude                          0
Latitude                           0
New Cases per Million              0
Total Cases per Million            0
New Deaths per Million             0
Total Deaths per Million           0
Total Deaths per 100rb             0
Case Fatality Rate                 0
Case Recovered Rate                0
Growth Factor of New Cases      1187
Growth Factor of New Deaths     2467
dtype: int64

In [6]:
#Cek Duplicated Row
df.duplicated().sum()

0

In [7]:
print(df.describe(exclude="O"))

          New Cases    New Deaths  New Recovered  New Active Cases  \
count  21759.000000  21759.000000   21759.000000      21759.000000
mean     391.293580     13.220415     377.310998          0.762167
std     2074.551043     76.482617    1999.062563        937.213509
min        0.000000      0.000000       0.000000     -25725.000000
25%        7.000000      0.000000       4.000000        -16.000000
50%       41.000000      1.000000      31.000000          0.000000
75%      151.000000      5.000000     143.000000         27.000000
max    56757.000000   2069.000000   48832.000000      36726.000000

        Total Cases   Total Deaths  Total Recovered  Total Active Cases  \
count  2.175900e+04   21759.000000     2.175900e+04        21759.000000
mean   8.525997e+04    2648.289352     7.671260e+04         5899.079002
std    3.685133e+05   11776.011067     3.403957e+05        27518.102431
min    1.000000e+00       0.000000     0.000000e+00        -2306.000000
25%    1.822500e+03      50.000000     1.038500e+03          182.000000
50%    1.078000e+04     283.000000     8.745000e+03          919.000000
75%    3.646450e+04    1050.000000     3.293250e+04         2607.500000
max    4.257243e+06  143858.000000     4.105680e+06       574135.000000

       City or Regency  Total Regencies  ...  Population Density  \
count              0.0     21759.000000  ...        21759.000000
mean               NaN        24.160256  ...          744.989784
std                NaN        68.708265  ...         2743.209719
min                NaN         1.000000  ...            8.590000
25%                NaN         7.000000  ...           47.790000
50%                NaN        11.000000  ...          103.840000
75%                NaN        18.000000  ...          262.700000
max                NaN       416.000000  ...        16334.310000

          Longitude      Latitude  New Cases per Million  \
count  21759.000000  21759.000000           21759.000000
mean     113.680803     -2.731868              29.393033
std        9.857587      3.608264              69.941090
min       96.910522     -8.682205               0.000000
25%      106.109004     -6.204699               1.750000
50%      113.417654     -2.461746               8.160000
75%      121.201093      0.212037              26.260000
max      138.696030      4.225615            1348.130000

       Total Cases per Million  New Deaths per Million  \
count             21759.000000            21759.000000
mean               6183.650588                0.852727
std               10288.123342                2.277310
min                   0.010000                0.000000
25%                 415.915000                0.000000
50%                2727.460000                0.180000
75%                7374.120000                0.750000
max               79663.790000               63.800000

       Total Deaths per Million  Total Deaths per 100rb  \
count              21759.000000            21759.000000
mean                 163.542156               16.354192
std                  254.195761               25.419595
min                    0.000000                0.000000
25%                   10.880000                1.090000
50%                   73.550000                7.350000
75%                  195.850000               19.585000
max                 1533.980000              153.400000

       Growth Factor of New Cases  Growth Factor of New Deaths
count                20572.000000                 19292.000000
mean                     1.395671                     1.074145
std                      3.080207                     1.578502
min                      0.000000                     0.000000
25%                      0.650000                     0.660000
50%                      0.990000                     1.000000
75%                      1.330000                     1.000000
max                    175.000000                   134.500000

[8 rows x 26 columns]

In [8]:
print(df.head(10))
df=df.fillna(df.mean())
print("Dataset yang sudah diproses Handling Missing Values dengan Mean : ")
print(df.head(10))

       Date Location ISO Code     Location  New Cases  New Deaths  \
0  3/1/2020             ID-JK  DKI Jakarta          2           0
1  3/2/2020             ID-JK  DKI Jakarta          2           0
2  3/2/2020               IDN    Indonesia          2           0
3  3/2/2020             ID-RI         Riau          1           0
4  3/3/2020             ID-JK  DKI Jakarta          2           0
5  3/3/2020               IDN    Indonesia          0           0
6  3/3/2020             ID-JB   Jawa Barat          1           1
7  3/3/2020             ID-RI         Riau          0           0
8  3/4/2020             ID-JK  DKI Jakarta          2           0
9  3/4/2020               IDN    Indonesia          0           0

   New Recovered  New Active Cases  Total Cases  Total Deaths  \
0              0                 2           39            20
1              0                 2           41            20
2              0                 2            2             0
3              0                 1            2             0
4              0                 2           43            20
5              0                 0            2             0
6              0                 0            1             1
7              0                 0            2             0
8              0                 2           45            20
9              0                 0            2             0

   Total Recovered  ...  Latitude New Cases per Million  \
0               41  ... -6.204699                  0.18
1               41  ... -6.204699                  0.18
2                0  ... -0.789275                  0.01
3                3  ...  0.511648                  0.16
4               41  ... -6.204699                  0.18
5                0  ... -0.789275                  0.00
6                8  ... -6.920432                  0.02
7                3  ...  0.511648                  0.00
8               41  ... -6.204699                  0.18
9                0  ... -0.789275                  0.00

   Total Cases per Million New Deaths per Million Total Deaths per Million  \
0                     3.60                   0.00                     1.84
1                     3.78                   0.00                     1.84
2                     0.01                   0.00                     0.00
3                     0.33                   0.00                     0.00
4                     3.96                   0.00                     1.84
5                     0.01                   0.00                     0.00
6                     0.02                   0.02                     0.02
7                     0.33                   0.00                     0.00
8                     4.15                   0.00                     1.84
9                     0.01                   0.00                     0.00

  Total Deaths per 100rb Case Fatality Rate Case Recovered Rate  \
0                   0.18             51.28%             105.13%
1                   0.18             48.78%             100.00%
2                   0.00              0.00%               0.00%
3                   0.00              0.00%             150.00%
4                   0.18             46.51%              95.35%
5                   0.00              0.00%               0.00%
6                   0.00            100.00%             800.00%
7                   0.00              0.00%             150.00%
8                   0.18             44.44%              91.11%
9                   0.00              0.00%               0.00%

  Growth Factor of New Cases  Growth Factor of New Deaths
0                        NaN                          NaN
1                        1.0                          1.0
2                        NaN                          NaN
3                        NaN                          NaN
4                        1.0                          1.0
5                        0.0                          1.0
6                        NaN                          NaN
7                        0.0                          1.0
8                        1.0                          1.0
9                        1.0                          1.0

[10 rows x 38 columns]
Dataset yang sudah diproses Handling Missing Values dengan Mean :
       Date Location ISO Code     Location  New Cases  New Deaths  \
0  3/1/2020             ID-JK  DKI Jakarta          2           0
1  3/2/2020             ID-JK  DKI Jakarta          2           0
2  3/2/2020               IDN    Indonesia          2           0
3  3/2/2020             ID-RI         Riau          1           0
4  3/3/2020             ID-JK  DKI Jakarta          2           0
5  3/3/2020               IDN    Indonesia          0           0
6  3/3/2020             ID-JB   Jawa Barat          1           1
7  3/3/2020             ID-RI         Riau          0           0
8  3/4/2020             ID-JK  DKI Jakarta          2           0
9  3/4/2020               IDN    Indonesia          0           0

   New Recovered  New Active Cases  Total Cases  Total Deaths  \
0              0                 2           39            20
1              0                 2           41            20
2              0                 2            2             0
3              0                 1            2             0
4              0                 2           43            20
5              0                 0            2             0
6              0                 0            1             1
7              0                 0            2             0
8              0                 2           45            20
9              0                 0            2             0

   Total Recovered  ...  Latitude New Cases per Million  \
0               41  ... -6.204699                  0.18
1               41  ... -6.204699                  0.18
2                0  ... -0.789275                  0.01
3                3  ...  0.511648                  0.16
4               41  ... -6.204699                  0.18
5                0  ... -0.789275                  0.00
6                8  ... -6.920432                  0.02
7                3  ...  0.511648                  0.00
8               41  ... -6.204699                  0.18
9                0  ... -0.789275                  0.00

   Total Cases per Million New Deaths per Million Total Deaths per Million  \
0                     3.60                   0.00                     1.84
1                     3.78                   0.00                     1.84
2                     0.01                   0.00                     0.00
3                     0.33                   0.00                     0.00
4                     3.96                   0.00                     1.84
5                     0.01                   0.00                     0.00
6                     0.02                   0.02                     0.02
7                     0.33                   0.00                     0.00
8                     4.15                   0.00                     1.84
9                     0.01                   0.00                     0.00

  Total Deaths per 100rb Case Fatality Rate Case Recovered Rate  \
0                   0.18             51.28%             105.13%
1                   0.18             48.78%             100.00%
2                   0.00              0.00%               0.00%
3                   0.00              0.00%             150.00%
4                   0.18             46.51%              95.35%
5                   0.00              0.00%               0.00%
6                   0.00            100.00%             800.00%
7                   0.00              0.00%             150.00%
8                   0.18             44.44%              91.11%
9                   0.00              0.00%               0.00%

  Growth Factor of New Cases  Growth Factor of New Deaths
0                   1.395671                     1.074145
1                   1.000000                     1.000000
2                   1.395671                     1.074145
3                   1.395671                     1.074145
4                   1.000000                     1.000000
5                   0.000000                     1.000000
6                   1.395671                     1.074145
7                   0.000000                     1.000000
8                   1.000000                     1.000000
9                   1.000000                     1.000000

[10 rows x 38 columns]

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.